name: refresh_state
description: Refresh state management gives devloper ease in state-management eliminating redundant code.
version: 0.0.2
homepage: https://github.com/abrarmalekji12/refresh_state

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
